apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: {{ $.Values.namespace.name }}
data:
  tempo.yaml: |
    {{- tpl (.Files.Get "configs/tempo.yaml") . | trimSuffix "\n" | nindent 4 }}
