apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-cluster-collector-config
  namespace: {{ $.Values.namespace.name }}
data:
  config.yaml: |
    {{- tpl (.Files.Get "configs/otel-cluster-collector.yaml") . | trimSuffix "\n" | nindent 4 }}
